[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"

# Next.js için gerekli ayarlar
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Functions configuration
[functions]
  node_bundler = "esbuild"

# Scheduled function for question processing
[functions."api-cron-process-questions"]
  schedule = "0 */6 * * *"  # Her 6 saatte bir çalışır
